version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing...
      - echo node version
      - node -v
      - echo npm version
      - npm -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: ./build
  files:
    - "**/*"
cache:
  paths:
    - "./node_modules/**/*"
